[tool.poetry]
name = "teleprint-me"
version = "0.1.0"
description = "My personal home page and public portfolio"
authors = ["Austin Berrio"]
license = "AGPL-3.0"
readme = "README.md"
packages = [{include = "teleprint_me"}]

[tool.poetry.dependencies]
python = "^3.10"
bottle = "^0.12.23"
WTForms = "^3.0.1"
peewee = "^3.15.3"

[tool.poetry.dev-dependencies]
bpython = "^0.23"
black = "^22.10.0"
flake8 = "^5.0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
